<?php

namespace FooBar;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Package\Locker;
use Composer\Plugin\PluginInterface;
use Composer\Script\Event;
use Composer\Script\ScriptEvents;

class Installer implements PluginInterface, EventSubscriberInterface
{
    private $generatedClassTemplate = <<<'PHP'
<?php

namespace FooBar;

/**
 * This class is generated by
 */
final class Versions
{
    const VERSIONS = %s;

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    private static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
PHP;

    /**
     * {@inheritDoc}
     */
    public function activate(Composer $composer, IOInterface $io)
    {
        $composer->getEventDispatcher()->addSubscriber($this);
    }

    /**
     * {@inheritDoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            ScriptEvents::POST_INSTALL_CMD => 'dumpVersionsClass',
            ScriptEvents::POST_UPDATE_CMD  => 'dumpVersionsClass',
        ];
    }

    /**
     * @param Event $composerEvent
     *
     * @return void
     */
    public function dumpVersionsClass(Event $composerEvent)
    {
        $io = $composerEvent->getIO();

        $io->write('<info>Generating version class...</info>');

        $this->writeVersionClassToFile(
            $this->generateVersionsClass($composerEvent->getComposer()),
            $composerEvent->getComposer()
        );

        $this->reDumpAutoloader($composerEvent->getComposer(), $composerEvent->getArguments());

        $io->write('<info>...done generating version class</info>');
    }

    private function generateVersionsClass(Composer $composer) : string
    {
        return sprintf(
            $this->generatedClassTemplate,
            var_export(iterator_to_array($this->getVersions($composer->getLocker())), true)
        );
    }

    private function writeVersionClassToFile(string $versionClassSource, Composer $composer)
    {
        //$rootPackage = $composer->getPackage();

        $vendorDir = $composer->getConfig()->get('vendor-dir');

        file_put_contents($vendorDir . '/yadda/yadda/src/FooBar/Versions.php', $versionClassSource, 0664);
    }

    private function reDumpAutoloader(Composer $composer, array $arguments)
    {
        $rootPackage         = $composer->getPackage();
        $installationManager = $composer->getInstallationManager();

        $composer->getAutoloadGenerator()->dump(
            $composer->getConfig(),
            $composer->getRepositoryManager()->getLocalRepository(),
            $rootPackage,
            $installationManager,
            'composer',
            true // CBA to provide this manually, for now
        );
    }

    /**
     * @param Locker $locker
     *
     * @return string[]|\Generator
     */
    private function getVersions(Locker $locker) : \Generator
    {
        die(var_dump($locker->getLockData()['packages']));
        foreach ($locker->getLockData()['packages'] as $package) {
            yield $package['name']
                => $package['name'] . '#' . $package['version'] . '@' . $package['dist']['reference'];
        }
    }
}